job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/milimehdi/Jenkins_Upgradev3_fork.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', '/Users/mehdimili/.jenkins/workspace/First-Maven-Project-Via-DSL/maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}